# LoadBalancer
apiVersion: v1
kind: Service
metadata:
  name: snaic-platform-loadbalancer
  labels:
    app: snaic-lb-service
spec:
  type: LoadBalancer
  ports:
    - protocol: "TCP"
      port: 3000
      targetPort: 3000
      nodePort: 32000
  selector:
    app: snaic-platform