# Triggers only when main is updated
trigger:
  branches:
    include:
      - main            # <- ‘main’ in Azure Repos

pr: none                # don’t run for PR validation

pool:
  vmImage: ubuntu-latest

steps:
# 1) Checkout the Azure Repos source
- checkout: self
  persistCredentials: true     # lets us fetch without re-auth

# 2) Push main → GitHub
- bash: |
    set -euxo pipefail

    git config --global user.email "build@dev.azure.com"
    git config --global user.name  "Azure DevOps Mirror Bot"

    # add the GitHub remote once (ignore if it already exists)
    git remote add github \
      https://x-access-token:${GITHUB_PAT}@github.com/saisnaic/SNAIC-PLATFORM.git \
      || true

    # push ONLY main + tags, overwriting history if you rewrote main
    git push --prune github +refs/heads/main:refs/heads/main --tags
  env:
    GITHUB_PAT: $(GITHUB_PAT)
  displayName: 'Mirror main → GitHub'
