# azure-pipelines-mirror.yml
# ─────────────────────────────────────────────────────────────
# Mirrors Azure Repos `main` → GitHub `main` whenever `main` changes

trigger:
  branches:
    include:
      - main        # Azure Repos branch to watch

pr: none            # don’t run for PR validation

variables:
  - group: GitHubSecrets         # secret GITHUB_PAT lives here

pool:
  vmImage: ubuntu-latest

steps:
# 1) Checkout source
- checkout: self
  persistCredentials: true
  fetchDepth: 0                  # full history (optional but nice)

# 2) Push the built commit to GitHub
- bash: |
    set -euxo pipefail

    # Identify automated pushes (only used if the script ever writes commits)
    git config --global user.email "build@dev.azure.com"
    git config --global user.name  "Azure DevOps Mirror Bot"

    # Add the GitHub remote if it isn’t already present
    git remote add github \
      https://x-access-token:${GITHUB_PAT}@github.com/saisnaic/SNAIC-PLATFORM.git \
      || true

    # One-time overwrite if GitHub has a diverging “initial commit”,
    # otherwise behaves as a normal fast-forward push.
    git push --force-with-lease --prune github HEAD:refs/heads/main --tags
  env:
    GITHUB_PAT: $(GITHUB_PAT)
  displayName: 'Mirror HEAD → GitHub main'
  # Run this step only when the pipeline itself was triggered by `main`
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')