# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: AzureContainerApps@1
      inputs:
        azureSubscription: 'Azure-Abonnement 1(55e7830a-1455-406c-9386-d9f0ef56eac6)'
        resourceGroup: 'snaic-platform'
        targetPort: 3000
        disableTelemetry: true
        containerAppName: 'snaic-ai-platform' 

