# Secrets
apiVersion: v1
kind: Secret
metadata:
  name: snaic-platform-secrets
type: Opaque
stringData:
  db_host: "e3dc54b4-3215-4863-9eec-2e649294eaf2.postgresql.eu01.onstackit.cloud"
  db_user: "flowise-user"
  db_password: "KK2i7qari8WR8dHev6rLW6fjV2K1W78a88LqZ7NpQApLyIYiGmmvzw5bAoW5Tf14"
  db_name: "snaic-platform"
  api_key: "apikey"